singleQuote: true
semi: false
printWidth: 100
trailingComma: none
overrides:
  - files: 'src/renderer-vue/**'
    options:
      tabWidth: 4
  - files: 'src/renderer-shared/**'
    options:
      tabWidth: 4
